<?php 
/** 
 * Include all the SVG interfaces in the 'types' category 
 */ 

include_once('SVGElement.php');
include_once('SVGAnimatedBoolean.php');
include_once('SVGAnimatedString.php');
include_once('SVGStringList.php');
include_once('SVGAnimatedEnumeration.php');
include_once('SVGAnimatedInteger.php');
include_once('SVGNumber.php');
include_once('SVGAnimatedNumber.php');
include_once('SVGNumberList.php');
include_once('SVGAnimatedNumberList.php');
include_once('SVGLength.php');
include_once('SVGAnimatedLength.php');
include_once('SVGLengthList.php');
include_once('SVGAnimatedLengthList.php');
include_once('SVGAngle.php');
include_once('SVGAnimatedAngle.php');
include_once('SVGColor.php');
include_once('SVGICCColor.php');
include_once('SVGRect.php');
include_once('SVGAnimatedRect.php');
include_once('SVGUnitTypes.php');
include_once('SVGStylable.php');
include_once('SVGLocatable.php');
include_once('SVGTransformable.php');
include_once('SVGTests.php');
include_once('SVGLangSpace.php');
include_once('SVGExternalResourcesRequired.php');
include_once('SVGFitToViewBox.php');
include_once('SVGZoomAndPan.php');
include_once('SVGViewSpec.php');
include_once('SVGURIReference.php');
include_once('SVGCSSRule.php');
include_once('SVGRenderingIntent.php');
